# GOAL DEFINITION

nav_msgs/Path path

# driving speed of robot (interpreted as recommended value)
float32 velocity

---
# RESULT DEFINITION

#uint8 MOTION_STATUS_STOP = 0   #TODO: unused
uint8 MOTION_STATUS_MOVING = 1 # FIXME: this makes no sense as a _result_ status
uint8 MOTION_STATUS_COLLISION = 2
uint8 MOTION_STATUS_SUCCESS = 3
#uint8 MOTION_STATUS_MOVE_FAIL = 4 #TODO: unused
uint8 MOTION_STATUS_INTERNAL_ERROR = 5
uint8 MOTION_STATUS_SLAM_FAIL = 6
#uint8 MOTION_STATUS_GOAL_FAIL = 7 #TODO: unused
uint8 MOTION_STATUS_PATH_LOST = 8
uint8 MOTION_STATUS_TIMEOUT = 9

int8 status

---
# FEEDBACK DEFINITION

uint8 MOTION_STATUS_MOVING = 1
uint8 MOTION_STATUS_COLLISION = 2

uint8 status

Obstacle[] obstacles_on_path
