# Define the goal
uint8 FAILURE_MODE_ABORT = 0
uint8 FAILURE_MODE_REPLAN = 1

uint8 INIT_MODE_STOP = 0
uint8 INIT_MODE_CONTINUE = 1

path_msgs/Goal goal

uint8 init_mode
uint8 failure_mode
float32 velocity

---
# Define the result
uint8 STATUS_OTHER_ERROR = 0
uint8 STATUS_SUCCESS = 1
uint8 STATUS_ABORTED = 2
uint8 STATUS_OBSTACLE = 3
uint8 STATUS_TIMEOUT = 4
uint8 STATUS_LOST_PATH = 5
uint8 STATUS_NO_PATH_FOUND = 6

bool reached_goal
uint8 status

---
# Define a feedback message
# Maybe something like distance to goal or elapsed time?

uint8 STATUS_MOVING = 1
uint8 STATUS_OBSTACLE = 2
uint8 STATUS_PATH_READY = 3
uint8 STATUS_REPLAN = 4
uint8 STATUS_REPLAN_FAILED = 5 # used if max num of replan attempts is reached without success

uint8 status

Obstacle[] obstacles_on_path
