#goal definition

geometry_msgs/PoseStamped current
Obstacle obstacle

geometry_msgs/PoseStamped goal

---
#result definition

path_msgs/PathSequence path

---
#feedback

uint8 STATUS_DONE = 0
uint8 STATUS_PLANNING = 1
uint8 STATUS_POST_PROCESSING = 2
uint8 STATUS_PLANNING_FAILED = 10

uint8 status
