STANN: bruteNN< Point > Class Template Reference
bruteNN< Point > Class Template Reference
A Brute force NN search class This class is a simple brute force algorithm for computing nearest neighbors. It is very innefficient and should be used only for accuracy tests.
#include <bruteNN.hpp>
Public Member Functions
bruteNN (Point *points, long int N)
Constructor Constructs a brute force nearest neighbor search structure out of the given data points.
~bruteNN ()
Destructor.
void ksearch (Point q, int k, std::vector< long unsigned int > &nn_idx)
Nearest neighbor search function.
void ksearch (Point q, int k, std::vector< long unsigned int > &nn_idx, std::vector< double > &d_index)
Nearest neighbor search function.
Detailed Description
template<typename Point>
class bruteNN< Point >
A Brute force NN search class This class is a simple brute force algorithm for computing nearest neighbors. It is very innefficient and should be used only for accuracy tests.
Constructor & Destructor Documentation
template<typename Point > bruteNN< Point >::bruteNN (Point * points, long int N) [inline]
Constructor Constructs a brute force nearest neighbor search structure out of the given data points.
Parameters:
*points Pointer to list of input points
N number of input points
Member Function Documentation
template<typename Point > void bruteNN< Point >::ksearch (Point q, int k, std::vector< long unsigned int > & nn_idx, std::vector< double > & d_index) [inline]
Nearest neighbor search function.
This function returns the nearest k neighbors from the data structure to the given query point, as well as the squared distance to the query point. The return vector contains the indexes to the answer points in the original data array passed at construction time.
Parameters:
q Query point
k number of neighbors to search for
nn_idx Vector in which answer is written
d_index Vector in which square distances are written
References qknn::answer(), and qknn::update().
template<typename Point > void bruteNN< Point >::ksearch (Point q, int k, std::vector< long unsigned int > & nn_idx) [inline]
Nearest neighbor search function.
This function returns the nearest k neighbors from the data structure to the given query point. The return vector contains the indexes to the answer points in the original data array passed at construction time.
Parameters:
q Query point
k number of neighbors to search for
nn_idx Vector in which answer is written
References qknn::answer(), qknn::set_size(), and qknn::update().
The documentation for this class was generated from the following file:
bruteNN.hpp