STANN: int_partition Class Reference
int_partition Class Reference
Implementation of a union find data structure.
#include <int_partition.hpp>
Public Member Functions
int_partition ()
Default Constructor.
void initialize (long int n)
Initializes the Union find data structure.
~int_partition ()
Default Destructor.
long int find (long int x)
Finds the root ancestor of a point.
void union_blocks (long int x, long int y)
Joins two blocks of points, and compresses the find path.
Detailed Description
Implementation of a union find data structure.
Int Partition Class
Constructor & Destructor Documentation
int_partition::int_partition () [inline]
Default Constructor.
Constructor
int_partition::~int_partition () [inline]
Default Destructor.
Destructor
Member Function Documentation
long int int_partition::find (long int x) [inline]
Finds the root ancestor of a point.
Find
Parameters:
x Index of the query point
Referenced by union_blocks().
void int_partition::initialize (long int n) [inline]
Initializes the Union find data structure.
Initialize function
Parameters:
n Number of points to be included in the union find
Referenced by gmst().
void int_partition::union_blocks (long int x, long int y) [inline]
Joins two blocks of points, and compresses the find path.
Union Blocks
Parameters:
x Index of first point to be joined
y Index of second point to be joined
References find().
The documentation for this class was generated from the following file:
int_partition.hpp