STANN: WSP< Point > Class Template Reference
WSP< Point > Class Template Reference
Implements functions needed by a Well Seperated Pair object.
#include <pwspd.hpp>
Public Member Functions
WSP ()
Default constructor.
WSP (index f, index s)
Construcs a WSP consisting of two comp_quad_tree_node elements.
long int size ()
returns the number of points in the WSP
double get_bccp_dist () const
returns the currently computed BCCP distance
bool bccp_done () const
returns true if the actual BCCP has been computed, false otherwise
WSP< Point > & operator= (const WSP< Point > b)
Assignment operator.
void bccp ()
computes the BCCP if it has not been For WSPs of small size (<32) this computes the BCCP by brute force. Otherwise it calls a recursive algorithm.
Public Attributes
void * first
Indicates either the first quadtree box, or point Initially, this pointer indcates the comp_quad_tree_node that is the first half of the well-seperated pair. After the BCCP is calculated, this because a pointer to a point, indicating it is half of the BCCP.
void * second
Indicates either the second quadtree box, or point Initially, this pointer indcates the comp_quad_tree_node that is the second half of the well-seperated pair. After the BCCP is calculated, this because a pointer to a point, indicating it is half of the BCCP.
double bccp_dist
Indicates either the BCCP distance, or the marginal BCCP distance If this value is negative, it indicates the current minimum possible BCCP distance known. If it is positive, it indicates the actual BCCP distance.
Detailed Description
template<typename Point>
class WSP< Point >
Implements functions needed by a Well Seperated Pair object.
Well Seperated Pair
Constructor & Destructor Documentation
template<typename Point> WSP< Point >::WSP () [inline]
Default constructor.
Constructor
References WSP< Point >::bccp_dist.
template<typename Point> WSP< Point >::WSP (index f, index s) [inline]
Construcs a WSP consisting of two comp_quad_tree_node elements.
Constructor
Parameters:
f First comp_quad_tree_node
s Second comp_quad_tree_node
References WSP< Point >::bccp_dist, dist_sq_between_quad_boxes(), and comp_quad_tree_node< Point >::low.
Member Function Documentation
template<typename Point> void WSP< Point >::bccp () [inline]
computes the BCCP if it has not been For WSPs of small size (<32) this computes the BCCP by brute force. Otherwise it calls a recursive algorithm.
BCCP
References WSP< Point >::bccp_done(), WSP< Point >::first, WSP< Point >::second, and WSP< Point >::size().
template<typename Point> bool WSP< Point >::bccp_done () const [inline]
returns true if the actual BCCP has been computed, false otherwise
BCCP done
References WSP< Point >::bccp_dist.
Referenced by WSP< Point >::bccp(), and WSP< Point >::size().
template<typename Point> double WSP< Point >::get_bccp_dist () const [inline]
returns the currently computed BCCP distance
get bccp distance
References WSP< Point >::bccp_dist.
template<typename Point> WSP<Point>& WSP< Point >::operator= (const WSP< Point > b) [inline]
Assignment operator.
Assignment Operator
References WSP< Point >::bccp_dist, WSP< Point >::first, and WSP< Point >::second.
template<typename Point> long int WSP< Point >::size () [inline]
returns the number of points in the WSP
size
References WSP< Point >::bccp_done(), WSP< Point >::first, and WSP< Point >::second.
Referenced by WSP< Point >::bccp().
Member Data Documentation
template<typename Point> double WSP< Point >::bccp_dist
Indicates either the BCCP distance, or the marginal BCCP distance If this value is negative, it indicates the current minimum possible BCCP distance known. If it is positive, it indicates the actual BCCP distance.
bccp_dist
Referenced by WSP< Point >::bccp_done(), WSP< Point >::get_bccp_dist(), WSP< Point >::operator=(), and WSP< Point >::WSP().
template<typename Point> void* WSP< Point >::first
Indicates either the first quadtree box, or point Initially, this pointer indcates the comp_quad_tree_node that is the first half of the well-seperated pair. After the BCCP is calculated, this because a pointer to a point, indicating it is half of the BCCP.
first
Referenced by WSP< Point >::bccp(), WSP< Point >::operator=(), and WSP< Point >::size().
template<typename Point> void* WSP< Point >::second
Indicates either the second quadtree box, or point Initially, this pointer indcates the comp_quad_tree_node that is the second half of the well-seperated pair. After the BCCP is calculated, this because a pointer to a point, indicating it is half of the BCCP.
second
Referenced by WSP< Point >::bccp(), WSP< Point >::operator=(), and WSP< Point >::size().
The documentation for this class was generated from the following file:
pwspd.hpp