STANN: qknn Class Reference
qknn Class Reference
Distance Priority Queue.
#include <qknn.hpp>
Public Member Functions
qknn ()
Constructor.
double topdist (void)
Largest distance.
void set_size (long unsigned int k)
Set Size.
long int top ()
Point with largest distance.
bool update (double dist, long int p)
Update queue.
void answer (std::vector< long unsigned int > &pl)
Create answer.
void answer (std::vector< long unsigned int > &pl, std::vector< double > &pd)
Create answer.
long unsigned int size ()
Size function.
Detailed Description
Distance Priority Queue.
Implements a priority queue for pairs of floating point distances and array indexes. The priority queue is ordered based on the squared distance stored in the first element of the pair.
Constructor & Destructor Documentation
qknn::qknn () [inline]
Constructor.
Creates an empty priority queue.
Member Function Documentation
void qknn::answer (std::vector< long unsigned int > & pl, std::vector< double > & pd) [inline]
Create answer.
Transforms the queue into a vector of indeces to points and a vector of squared distances
Parameters:
pl Vector which holds the point indeces after function completes
pd Vector which holds the squared distances from query point
void qknn::answer (std::vector< long unsigned int > & pl) [inline]
Create answer.
Transforms the queue into a vector of indeces to points and returns it
Parameters:
pl Vector which will hold the answer after function completes
Referenced by sfcnn_ip< Point, DIM, CType >::ksearch(), and bruteNN< Point >::ksearch().
void qknn::set_size (long unsigned int k) [inline]
Set Size.
Sets the size of the priority queue. This should be set before the queue is used
Parameters:
k The maximum number of elements to be stored in the queue.
Referenced by bruteNN< Point >::ksearch().
long unsigned int qknn::size () [inline]
Size function.
Returns the current size of the queue
Returns:
Size
Referenced by update().
long int qknn::top () [inline]
Point with largest distance.
Returns the index associated with the largest element in the queue.
Returns:
Index of largest (most distant) element
double qknn::topdist (void) [inline]
Largest distance.
Returns the largest distance value stored in the priority queue
Returns:
Largest distance value
Referenced by update().
bool qknn::update (double dist, long int p) [inline]
Update queue.
Updates the queue with the given distance and point
Parameters:
dist Distance of point to be added
p index of point to be added
Returns:
True if a point was added to the queue
References size(), and topdist().
Referenced by bruteNN< Point >::ksearch().
The documentation for this class was generated from the following file:
qknn.hpp